config:
  info: springcloud/config-dev.yml varsion=7 msg=我是开发版
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8000/eureka/
